services:
  backend:
    build:
      context: ./app
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:5000 --workers 6 app:app
    networks:
      - cats

  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /var/log/cats:/var/log/nginx
    networks:
      - cats
    ports:
      - 80:80
    depends_on:
      - backend

networks:
  cats:
